
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry txtUser;

	private global::Gtk.Entry txtPassword;

	private global::Gtk.Entry txtHost;

	private global::Gtk.Label lblHost;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Button btnLogin;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtUser = new global::Gtk.Entry();
		this.txtUser.CanFocus = true;
		this.txtUser.Name = "txtUser";
		this.txtUser.IsEditable = true;
		this.txtUser.InvisibleChar = '•';
		this.fixed1.Add(this.txtUser);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtUser]));
		w1.X = 120;
		w1.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPassword = new global::Gtk.Entry();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.Visibility = false;
		this.txtPassword.InvisibleChar = '•';
		this.fixed1.Add(this.txtPassword);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtPassword]));
		w2.X = 120;
		w2.Y = 84;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtHost = new global::Gtk.Entry();
		this.txtHost.CanFocus = true;
		this.txtHost.Name = "txtHost";
		this.txtHost.IsEditable = true;
		this.txtHost.InvisibleChar = '•';
		this.fixed1.Add(this.txtHost);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtHost]));
		w3.X = 121;
		w3.Y = 22;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblHost = new global::Gtk.Label();
		this.lblHost.Name = "lblHost";
		this.lblHost.LabelProp = global::Mono.Unix.Catalog.GetString("Host:");
		this.fixed1.Add(this.lblHost);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblHost]));
		w4.X = 78;
		w4.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Username:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w5.X = 43;
		w5.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Password:");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w6.X = 46;
		w6.Y = 88;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLogin = new global::Gtk.Button();
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.BorderWidth = ((uint)(3));
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.fixed1.Add(this.btnLogin);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLogin]));
		w7.X = 223;
		w7.Y = 121;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 295;
		this.DefaultHeight = 167;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnLogin.Clicked += new global::System.EventHandler(this.onBtnLoginClick);
	}
}
